/* eslint-disable react/no-unescaped-entities */
function Section5() {
  return (
    <div className="lg:w-3/5 w-11/12 md:w-4/5 mb-5 py-5 flex flex-col gap-3">
      <p className="font-medium text-base text-justify">
        COCA-COLA: CARBONATED WATER. COCA-COLA IS A REGISTERED TRADEMARK OF THE
        COCA-COLA COMPANY. VEGETARIAN PRODUCT.
      </p>
      <p className="font-medium text-base text-justify">
        COCA-COLA ZERO SUGAR: CARBONATED WATER. CONTAINS NON-CALORIC SWEETENER.
        THIS CARBONATED WATER CONTAINS AN ADMIXTURE OF SUCRALOSE AND ACESULFAME
        POTASSIUM. NOT RECOMMENDED FOR CHILDREN, PREGNANT AND LACTATING MOTHERS.
        TRADEMARK OWNER: THE COCA-COLA COMPANY. VEGETARIAN PRODUCT.
      </p>
      <p className="font-medium text-base text-justify">
        DIET COKE: CARBONATED WATER. CONTAINS AN ADMIXTURE OF ASPARTAME AND
        ACESULFAME POTASSIUM. NOT RECOMMENDED FOR PHENYLKETONURICS; FOR
        CHILDREN; PREGNANT AND LACTATING MOTHERS. COKE IS A REGISTERED TRADEMARK
        OF THE COCA-COLA COMPANY. VEGETARIAN PRODUCT.
      </p>
      <p className="font-medium text-base text-justify">
        SPRITE: CARBONATED WATER. SPRITE IS A REGISTERED TRADEMARK OF THE
        COCA-COLA COMPANY. VEGETARIAN PRODUCT.
      </p>
      <p className="font-medium text-base text-justify">
        THUMS UP: CARBONATED WATER. THUMS UP IS A REGISTERED TRADEMARK OF THE
        COCA-COLA COMPANY. VEGETARIAN PRODUCT.
      </p>
      <p className="font-medium text-base text-justify">
        LIMCA: CARBONATED WATER. ADDED LIME AND LEMON FLAVORS. 'LIME AND LEMONI'
        IS A CREATIVE EXPRESSION USED FOR LIMCA. LIMCA IS A REGISTERED TRADEMARK
        OF THE COCA-COLA COMPANY. VEGETARIAN PRODUCT.
      </p>
      <p className="font-medium text-base text-justify">
        LIMCA SPORTZ: READY TO SERVE FRUIT BEVERAGE. *CONTAINS CARBOHYDRATE
        (INCLUDES 2.2% GLUCOSE) AND WITH ELECTROLYTES (SODIUM, POTASSIUM,
        CHLORIDE) WHICH HELP IN FASTER REHYDRATION THROUGH QUICK REPLACEMENT OF
        FLUID AND SALTS LOST IN SWEAT. LIMCA IS A REGISTERED TRADEMARK OF THE
        COCA-COLA COMPANY. VEGETARIAN PRODUCT.
      </p>
      <p className="font-medium text-base text-justify">
        FANTA: CARBONATED WATER. FANTA IS A REGISTERED TRADEMARK OF THE
        COCA-COLA COMPANY. VEGETARIAN PRODUCT.
      </p>
      <p className="font-medium text-base text-justify">
        FANTA APPLE DELITE: CARBONATED FRUIT BEVERAGE. CONTAINS 10.5% APPLE
        JUICE. CONTAINS NO FRUIT PIECES. "BITE" REFERS TO CRISPY, CRUNCHY TASTE
        OF APPLE. FANTA IS A REGISTERED TRADEMARK OF THE COCA-COLA COMPANY.
        VEGETARIAN PRODUCT.
      </p>
      <p className="font-medium text-base text-justify">
        MAAZA ORIGINAL: READY TO SERVE FRUIT DRINK. MAAZA MANGO CONTAINS BLEND
        OF MANGO PULP INCLUDING ALPHONSO. MAAZA IS A REGISTERED TRADEMARK OF THE
        COCA-COLA COMPANY
      </p>
      <p className="font-medium text-base text-justify">
        MAAZA AAM PANNA: READY TO SERVE FRUIT DRINK. MAAZA AAM PANNA IS A
        REGISTERED TRADEMARK OF THE COCA-COLA COMPANY
      </p>
      <p className="font-medium text-base text-justify">
        SCHWEPPES BITTER LEMON, SCHWEPPES MINT MOJITO: CARBONATED WATER.
        SCHWEPPES IS A REGISTERED TRADEMARK OF EUROPEAN REFRESHMENTS UNLIMITED
        COMPANY. DRINK RESPONSIBLY.
      </p>
      <p className="font-medium text-base text-justify">
        CHARGED BY THUMS UP: CAFFEINATED BEVERAGE. *CHARGED BY THUMS UP HAS 2.8
        TIMES CAFFEINE COMPARED TO REGULAR 250ml THUMS UP. CONTAINS ADDED BERRY
        FLAVOURS. HIGH CAFFEINE: 62.5mg/250ml. NOT RECOMMENDED FOR CHILDREN,
        PREGNANT OR LACTATING WOMEN, PERSONS SENSITIVE TO CAFFEINE. CONSUME NOT
        MORE THAN 500ml PER DAY. THUMS UP IS A REGISTERED TRADEMARK OF THE
        COCA-COLA COMPANY. * MRP INCLUSIVE OF ALL TAXES. VEGETARIAN PRODUCT.
      </p>
    </div>
  );
}

export default Section5;
